### ISSUE TITLE
Add more usage examples

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-rs#116]
It is beneficial to have these use cases available in the examples folder as separate runnable files:
- [ ] All supported data types in a single structure (could make the [enums.rs](https://github.com/ClickHouse/clickhouse.rs/blob/master/examples/enums.rs) example obsolete?) 
  - All "basic" types, including:
    - Chrono DateTime (https://github.com/ClickHouse/clickhouse.rs/issues/1)
    - (U)Int256 with its workarounds (see https://github.com/ClickHouse/clickhouse.rs/issues/48)
    - Highest precision decimals
  - Advanced types - maps/arrays/tuples/arrays of all this, nested, etc. This will close:
    - https://github.com/ClickHouse/clickhouse.rs/issues/101
    - https://github.com/ClickHouse/clickhouse.rs/issues/114
    - https://github.com/ClickHouse/clickhouse.rs/issues/72 (not sure)
- [x] ClickHouse Cloud connection + DDL example (`wait_end_of_query`, `select_sequential_consistency` settings highlight)
- [x] General ClickHouse settings usage via `.with_option`
- [x] `async_insert` - with and without `wait_for_async_insert`, using just `.with_option`; if it works (it should), this closes https://github.com/ClickHouse/clickhouse.rs/issues/65 as no additional code is required
- [x] `query_id`, cancel and kill queries - similarly to https://github.com/ClickHouse/clickhouse-js/blob/main/examples/cancel_query.ts, outline the diff between TCP and HTTP behaviors 
- [x] `session_id`, maybe with views; outline potential LB issues and lack of sticky sessions
- [ ] Request timeout (using tokio)
- [ ] Parameters binding
- [ ] Escaped SQL example (https://github.com/ClickHouse/clickhouse.rs/issues/96)
- [x] Custom HTTP client (https://github.com/ClickHouse/clickhouse.rs/issues/47)
- [ ] Advanced query usage: https://github.com/ClickHouse/clickhouse.rs/issues/53

**Comment by joshstevens19** [comment]
Is there no example of how to use an HTTPS clienthouse URL it seems not and hard to find examples of this

**Comment by slvrtrn** [comment]
@joshstevens19, you could use this example: https://github.com/ClickHouse/clickhouse-rs/blob/master/examples/clickhouse_cloud.rs, as CH Cloud is HTTPS.
